package com.zoro.paymentservice.services.paymentgateway;

import com.razorpay.RazorpayClient;
import org.springframework.stereotype.Service;

@Service
public class RazorpayPaymentGateway implements PaymentGateway{
    private RazorpayClient razorpayClient;
    public RazorpayPaymentGateway(RazorpayClient razorpayClient){
        this.razorpayClient = razorpayClient;
    }
    @Override
    public String generatePaymentLink(String orderId, String name, Long amount) {
        return "Payment link generated by Razorpay for order id: "+orderId;
    }
}
